server:
  port: 80
  context-path: /demo
  
spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false #关闭缓存
    content-type: text/html
    mode: LEGACYHTML5
    prefix: classpath:/templates/ #添加路径前缀
   

    