server:
  port: 80
  context-path: /demo
  
spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false #关闭缓存
    content-type: text/html
    mode: LEGACYHTML5
    prefix: classpath:/templates/ #添加路径前缀
  dataSource:
    url: jdbc:mysql://localhost:3306/demo?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: user@2019
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  typeAliasesPackage: com.demo.entity
  mapperLocations: classpath:mapper/*.xml
    
   

    